/**
 * File/folder icon resolver using Bearded Icons (GPL-3.0).
 *
 * Resolution order:
 *   1. Exact filename match (case-insensitive)
 *   2. Compound extension match (e.g. ".spec.ts" → testts)
 *   3. Simple extension match (e.g. ".rs" → rust)
 *   4. Fallback to generic "file" icon
 *
 * Icon SVGs live in /static/icons/bearded/.
 */

// Exact filename → icon name (lowercased keys for case-insensitive lookup)
const fileNameMap: Record<string, string> = {
  'cargo.toml': 'cargo',
  'cargo.lock': 'cargolock',
  'package.json': 'npm',
  'package-lock.json': 'npmlock',
  'bun.lockb': 'bunlock',
  'bun.lock': 'bunlock',
  'bunfig.toml': 'bun',
  'pnpm-lock.yaml': 'pnpmlock',
  'yarn.lock': 'yarnlock',
  'tsconfig.json': 'tsconfig',
  'tsconfig.app.json': 'tsconfig',
  'tsconfig.base.json': 'tsconfig',
  'tsconfig.node.json': 'tsconfig',
  'jsconfig.json': 'jsconfig',
  'svelte.config.js': 'svelteconfig',
  'svelte.config.ts': 'svelteconfig',
  'vite.config.js': 'vite',
  'vite.config.ts': 'vite',
  'vite.config.mjs': 'vite',
  'vite.config.mts': 'vite',
  'tailwind.config.js': 'tailwind',
  'tailwind.config.ts': 'tailwind',
  'tailwind.config.cjs': 'tailwind',
  'tailwind.config.mjs': 'tailwind',
  'postcss.config.js': 'postcssconfig',
  'postcss.config.cjs': 'postcssconfig',
  'postcss.config.mjs': 'postcssconfig',
  '.postcssrc': 'postcssconfig',
  'tauri.conf.json': 'tauri',
  'tauri.conf.json5': 'tauri',
  'tauri.linux.conf.json': 'tauri',
  'tauri.windows.conf.json': 'tauri',
  'tauri.macos.conf.json': 'tauri',
  '.gitignore': 'git',
  '.gitattributes': 'git',
  '.gitmodules': 'git',
  '.gitconfig': 'git',
  '.gitkeep': 'git',
  '.git-blame-ignore-revs': 'git',
  dockerfile: 'docker',
  'docker-compose.yml': 'docker',
  'docker-compose.yaml': 'docker',
  '.dockerignore': 'dockerignore',
  '.eslintrc': 'eslint',
  '.eslintrc.js': 'eslint',
  '.eslintrc.json': 'eslint',
  '.eslintrc.cjs': 'eslint',
  'eslint.config.js': 'eslint',
  'eslint.config.ts': 'eslint',
  'eslint.config.mjs': 'eslint',
  'eslint.config.cjs': 'eslint',
  '.eslintignore': 'eslintignore',
  '.prettierrc': 'prettier',
  '.prettierrc.js': 'prettier',
  '.prettierrc.json': 'prettier',
  '.prettierrc.yml': 'prettier',
  'prettier.config.js': 'prettier',
  'prettier.config.ts': 'prettier',
  '.prettierignore': 'prettierignore',
  'readme.md': 'readme',
  'readme.txt': 'readme',
  license: 'license',
  licence: 'license',
  'license.md': 'license',
  'license.txt': 'license',
  'licence.md': 'license',
  'licence.txt': 'license',
  makefile: 'makefile',
  '.env': 'env',
  '.env.local': 'env',
  '.env.dev': 'env',
  '.env.development': 'env',
  '.env.prod': 'env',
  '.env.production': 'env',
  '.env.staging': 'env',
  '.env.test': 'env',
  '.env.example': 'env',
  '.env.sample': 'env',
  'flake.lock': 'flakelock',
  'go.mod': 'go_package',
  'go.sum': 'go_package',
  'composer.json': 'composer',
  'composer.lock': 'composerlock',
  gemfile: 'bundler',
  'gemfile.lock': 'bundler',
  '.ruby-version': 'bundler',
  rakefile: 'ruby',
  pipfile: 'pip',
  'pipfile.lock': 'pip',
  'pyproject.toml': 'pyproject',
  'poetry.toml': 'poetry',
  'poetry.lock': 'poetrylock',
  'pubspec.yaml': 'flutter',
  'pubspec.lock': 'flutterlock',
  'mix.exs': 'mix',
  'mix.lock': 'mixlock',
  'rustfmt.toml': 'rustfmt',
  '.rustfmt.toml': 'rustfmt',
  'rust-toolchain': 'rust_toolchain',
  'todo.md': 'todo',
  'todo.txt': 'todo',
  todo: 'todo',
  'claude.md': 'claude',
  '.editorconfig': 'editorconfig',
  'rollup.config.js': 'rollup',
  'rollup.config.mjs': 'rollup',
  'rollup.config.ts': 'rollup',
  '.npmrc': 'npm',
  '.npmignore': 'npm',
  '.nvmrc': 'nvm',
  '.node-version': 'node',
  'nodemon.json': 'nodemon',
  'jest.config.js': 'jest',
  'jest.config.ts': 'jest',
  'jest.config.json': 'jest',
  'vitest.config.ts': 'vitest',
  'vitest.config.js': 'vitest',
  'vitest.workspace.ts': 'vitest',
  'cypress.config.ts': 'cypress',
  'cypress.config.js': 'cypress',
  'playwright.config.ts': 'playright',
  'playwright.config.js': 'playright',
  '.travis.yml': 'travis',
  '.gitlab-ci.yml': 'gitlab',
  'netlify.toml': 'netlify',
  'vercel.json': 'vercel',
  'now.json': 'vercel',
  'turbo.json': 'turbo',
  'turbo.jsonc': 'turbo',
  'nx.json': 'nx',
  'biome.json': 'biome',
  'rome.json': 'rome',
  '.commitlintrc': 'commitlint',
  'commitlint.config.js': 'commitlint',
  'commitlint.config.ts': 'commitlint',
  'lerna.json': 'lerna',
  'pom.xml': 'maven',
  'nginx.conf': 'nginx',
  'favicon.ico': 'favicon',
  'robots.txt': 'robots',
  '.htaccess': 'htaccess',
  '.pre-commit-config.yaml': 'precommit',
  '.huskyrc': 'husky',
  'husky.config.js': 'husky',
  '.lintstagedrc': 'lintstagedrc',
  'lint-staged.config.js': 'lintstagedrc',
  'drizzle.config.ts': 'drizzle',
  'drizzle.config.js': 'drizzle',
  'next.config.js': 'nextconfig',
  'next.config.mjs': 'nextconfig',
  'next.config.ts': 'nextconfig',
  'nuxt.config.js': 'nuxt',
  'nuxt.config.ts': 'nuxt',
  'astro.config.js': 'astroconfig',
  'astro.config.ts': 'astroconfig',
  'astro.config.mjs': 'astroconfig',
  'remix.config.js': 'remix',
  'remix.config.ts': 'remix',
  'esbuild.js': 'esbuild',
  'esbuild.ts': 'esbuild',
  'xmake.lua': 'xmake',
  '.cursorrules': 'cursor',
  'cmakelists.txt': 'cmake',
  'launch.json': 'launch',
  'tasks.json': 'vscode',
  'manifest.json': 'manifest',
  '.stylelintrc': 'stylelint',
  'stylelint.config.js': 'stylelint',
  '.stylelintignore': 'stylelintignore'
}

// Compound extensions (checked before simple extension)
const compoundExtMap: Record<string, string> = {
  'd.ts': 'typescriptdef',
  'spec.ts': 'testts',
  'spec.tsx': 'testts',
  'spec.js': 'testjs',
  'spec.jsx': 'testjs',
  'test.ts': 'testts',
  'test.tsx': 'testts',
  'test.js': 'testjs',
  'test.jsx': 'testjs',
  'test.mjs': 'testjs',
  'test.cjs': 'testjs',
  'test.mts': 'testts',
  'test.cts': 'testts',
  'e2e-spec.ts': 'testts',
  'e2e-test.ts': 'testts',
  'stories.js': 'storybook',
  'stories.jsx': 'storybook',
  'stories.ts': 'storybook',
  'stories.tsx': 'storybook',
  'stories.svelte': 'storybook',
  'story.js': 'storybook',
  'story.ts': 'storybook',
  'story.svelte': 'storybook',
  'module.ts': 'nestjsmodule',
  'service.ts': 'nestjsservice',
  'controller.ts': 'nestjscontroller',
  'cy.ts': 'cypressts',
  'cy.js': 'cypressjs'
}

// Simple extension → icon name
const extMap: Record<string, string> = {
  ts: 'typescript',
  tsx: 'reactts',
  js: 'js',
  jsx: 'reactjs',
  mjs: 'js',
  cjs: 'js',
  mts: 'typescript',
  cts: 'typescript',
  json: 'json',
  json5: 'json5',
  svelte: 'svelte',
  rs: 'rust',
  go: 'go',
  py: 'python',
  rb: 'ruby',
  java: 'java',
  kt: 'kotlin',
  kts: 'kotlins',
  swift: 'swift',
  c: 'c',
  h: 'cheader',
  cpp: 'cpp',
  hpp: 'hpp',
  cs: 'csharp',
  fs: 'fsharp',
  dart: 'dartlang',
  ex: 'elixir',
  exs: 'exs',
  erl: 'erlang',
  hs: 'haskell',
  elm: 'elm',
  clj: 'clojure',
  cljs: 'clojure',
  scala: 'scala',
  sc: 'scala',
  zig: 'zig',
  nim: 'nim',
  v: 'v',
  odin: 'odin',
  gleam: 'gleam',
  wasm: 'wasm',
  html: 'html',
  htm: 'html',
  css: 'css',
  scss: 'scss',
  sass: 'scss',
  less: 'less',
  styl: 'stylus',
  vue: 'vue',
  astro: 'astro',
  md: 'markdown',
  mdx: 'markdownx',
  txt: 'txt',
  csv: 'csv',
  xml: 'xml',
  yaml: 'yaml',
  yml: 'yaml',
  toml: 'toml',
  ini: 'conf',
  cfg: 'conf',
  conf: 'conf',
  env: 'env',
  sql: 'sql',
  sqlite: 'sqlite',
  sqlite3: 'sqlite',
  db: 'sqlite',
  graphql: 'graphql',
  gql: 'graphql',
  proto: 'proto',
  prisma: 'prisma',
  sh: 'shell',
  bash: 'shell',
  zsh: 'shell',
  fish: 'shell',
  ps1: 'powershell',
  bat: 'bat',
  cmd: 'cli',
  nix: 'nix',
  lock: 'lock',
  log: 'log',
  diff: 'diff',
  patch: 'diff',
  sol: 'sol',
  tf: 'terraform',
  hcl: 'hashicorp',
  lua: 'lua',
  vim: 'vim',
  tex: 'latex',
  pdf: 'pdf',
  doc: 'word',
  docx: 'word',
  xls: 'excel',
  xlsx: 'excel',
  ppt: 'powerpoint',
  pptx: 'powerpoint',
  png: 'imagepng',
  jpg: 'imagejpg',
  jpeg: 'imagejpg',
  gif: 'imagegif',
  svg: 'svg',
  ico: 'imageico',
  webp: 'imagewebp',
  mp3: 'audiomp3',
  wav: 'audiowav',
  ogg: 'audioogg',
  mp4: 'mp4',
  mov: 'mov',
  zip: 'zip',
  tar: 'zip',
  gz: 'zip',
  bz2: 'zip',
  xz: 'zip',
  '7z': 'zip',
  rar: 'zip',
  tgz: 'zip',
  woff: 'fontwoff',
  woff2: 'fontwoff2',
  ttf: 'fontttf',
  otf: 'fontotf',
  eot: 'fonteot',
  pem: 'key',
  key: 'key',
  cer: 'cert',
  crt: 'cert',
  p12: 'cert',
  pfx: 'pfx',
  hbs: 'handlebars',
  mustache: 'mustache',
  ejs: 'ejs',
  pug: 'pug',
  twig: 'twig',
  liquid: 'liquid',
  njk: 'njk',
  erb: 'erb',
  php: 'php',
  pl: 'perl',
  r: 'r',
  jl: 'julia',
  ipynb: 'ipynb',
  dockerfile: 'docker',
  makefile: 'makefile',
  cmake: 'cmake',
  gradle: 'gradle',
  groovy: 'groovy',
  jar: 'jar',
  war: 'jar',
  class: 'class',
  exe: 'binary',
  dll: 'binary',
  so: 'binary',
  o: 'binary',
  bin: 'binary',
  ron: 'ron',
  feature: 'cucumber'
}

// Bearded Icons doesn't ship per-folder-name SVGs — the _fd_* mapping
// names are VS Code icon-definition stubs that all fall back to the
// generic folder icon. We use folder.svg / folder_open.svg directly.

const ICON_BASE = '/icons/bearded'

/**
 * Resolve the icon path for a given filename.
 * Returns a URL path to the SVG in /static/icons/bearded/.
 */
export function resolveFileIcon(filename: string): string {
  const base = filename.includes('/') ? filename.split('/').pop()! : filename
  const lower = base.toLowerCase()

  // 1. Exact filename match
  if (fileNameMap[lower]) {
    return `${ICON_BASE}/${fileNameMap[lower]}.svg`
  }

  // 2. Compound extension match (greedy: check longest suffix first)
  const dotIndex = lower.indexOf('.')
  if (dotIndex !== -1) {
    const afterFirstDot = lower.slice(dotIndex + 1)
    if (compoundExtMap[afterFirstDot]) {
      return `${ICON_BASE}/${compoundExtMap[afterFirstDot]}.svg`
    }
    // Also check from the second dot for patterns like "foo.spec.ts"
    const secondDot = afterFirstDot.indexOf('.')
    if (secondDot !== -1) {
      const compoundExt = afterFirstDot.slice(secondDot + 1)
      if (compoundExtMap[compoundExt]) {
        return `${ICON_BASE}/${compoundExtMap[compoundExt]}.svg`
      }
    }
  }

  // 3. Simple extension match
  const lastDot = lower.lastIndexOf('.')
  if (lastDot !== -1) {
    const ext = lower.slice(lastDot + 1)
    if (extMap[ext]) {
      return `${ICON_BASE}/${extMap[ext]}.svg`
    }
  }

  // 4. Fallback
  return `${ICON_BASE}/file.svg`
}

/**
 * Resolve folder icon path.
 * Uses the generic bearded folder / folder_open SVGs.
 */
export function resolveFolderIcon(_folderName: string, expanded: boolean): string {
  return expanded ? `${ICON_BASE}/folder_open.svg` : `${ICON_BASE}/folder.svg`
}
